huggingface:
  provider: nebius
  api_key_env: HUGGINGFACE_HUB_TOKEN
  model: black-forest-labs/FLUX.1-dev

image:
  width: 128
  height: 128
  resize: true
  extension: .png
  resize_width: 128
  resize_height: 128
  style_prompt: |
    A clean, minimalist pencil sketch of {input_text} designed as a slot
    machine reel symbol. Sharp black outlines, no shading, 
    transparent background, simple line art style, optimized 
    for 128x128 resolution icon, clear and easily recognizable.

inputs:
  - skeleton