llm:
  model: "gemini-2.0-flash-001"
  temperature: 0.0

prompt:
  template: |
    **User Input:**
        {input_text}
        {exclude_sections}
    ***Instruction***:
    As a game designer , I want to create a story driven slot game concept based on User Input.
    Customize as per the User Input.
    Consider player's nature from User Input if available
    Consider core story from User Input if available
    Consider platform from User Input if available
    Consider reel layout from User Input if available
    Consider tone from User Input if available.
    Consider theme from User Input if available.
    Limit the number of characters to 3.
    If a certain input is missing, make an educated guess based on the User Input and context.
    Make the concept original, appealing, and aligned with the given theme. Include the unique twists.
    If specified to not include characters in the output. Do not include characters
    Else include characters
    If specified to not include bonusFeatures in the output. Do not include bonusFeatures
    Else include bonusFeatures
    If specified to not include symbols in the output. Do not include symbols
    Else include symbols
    If specified to not include visualStyle in the output. Do not include visualStyle
    Else include visualStyle
 
    **Context:** A story-based slot game concept
    consider [player's type like e.g casual , aggressive].
    Narrative led slot game experience is appreciated.
    The slot game has an engaging story that explains the setting, the [core story].
    The game has a [theme e.g Adventure & Exploration, Classic & Retro, Fantasy , Sci-ficion ].
    The game has a [tone like e.g Humourous, Luxurious, Heroic].
   
    The game story progresses through mechanics like [ like e.g level-ups, unlocking reels, completing chapter].
 
    The game characters match the story.
    The game characters match the tone.
 
   
    The reels of the slot game match thematic symbol , symbols can be of type [symbols type like e.g Regular, Scatter Symbols].
    The symbols match the theme and tone.
   
    The game has [bonus features like e.g. Free Spins, Progressive Jackpots, Respin features, Bonus wheels] to enhance engagement.
    The game has to be adaptable for [platforms like e.g.  mobile , desktop].
    The slot games have reel with [reel layout size  e.g. 4x4 reels].
 
    The game has a final hook , a punch line that sort of challeges and arouse curosity in the player.
    The story and elements will be used a guide for developing a slot game.
 
        {format_instructions}