image_generation_enable: true
huggingface:
  provider: nebius
  model: black-forest-labs/FLUX.1-dev

nebius:
  model: black-forest-labs/flux-dev
  response_extension: png
  base_url: "https://api.studio.nebius.com/v1/"
  response_format: "b64_json"

image:
  width: 512
  height: 512
  resize: true
  extension: .png
  resize_width: 512
  resize_height: 512
  directory_name: images
  style_prompt: |
    A black and white pencil sketch illustration of {name}, described as: {description}. 
    The symbol should be centered in the frame, full-body, with no cropping, no distortion, and properly framed in a 1:1 aspect ratio. 
    Rendered on a plain white background, suitable for PNG format with clean transparent-style edges. 
    Drawn in minimalist, clean pencil strokes with high contrast and sharp outlines. 
    The symbol must be distinct, readable, and optimized for slot game usage. 
    Game theme: {game_theme}.