huggingface:
  provider: nebius
  model: black-forest-labs/FLUX.1-dev

image:
  width: 128
  height: 128
  resize: true
  extension: .png
  resize_width: 128
  resize_height: 128
  directory_name: images
  style_prompt: |
    Minimalist pencil sketch of {name}, featuring {description}, 
    drawn in {art_style}. Styled as a slot machine reel symbol,
    using clean black outlines, no shading, and a transparent background. 
    Designed in a simple line art style, optimized for 128x128 icon resolution—clear, distinct, and easily recognizable
